implement faster point distribution in Grid
prime-slam/octreelib pull request #19
Opened 2023-11-22 10:25 UTC by true-real-michael

2023-11-22 12:22 UTC, pmokeev requested changes

2023-11-22 12:22 UTC, pmokeev commented on octreelib/grid/grid.py
> +        voxel_indices = voxel_indices.astype(int)
Наверное это можно сразу строкой выше сделать, в другой функции ты так и сделал

2023-11-22 12:22 UTC, pmokeev commented on octreelib/octree/octree.py
> +                )
Вот тут не совсем понятно что за индексы 4 и 2

2023-11-22 16:36 UTC, true-real-michael commented on octreelib/grid/grid.py
> +        voxel_indices = voxel_indices.astype(int)
исправил

2023-11-22 16:44 UTC, true-real-michael commented on octreelib/octree/octree.py
> +                )
исправил

2023-11-23 15:34 UTC, pmokeev approved these changes

2023-11-23 15:53 UTC, merged